{
 "title": "All Nodes",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Top 10 Nodes: High Memory Usage",
   "type": "graph",
   "description": "Top 10 nodes that use a lot of memory",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(topk(10, (node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / (node_memory_MemTotal_bytes ))) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worst 10 Nodes: Low CPU idle time",
   "type": "graph",
   "description": "Worst 10 nodes with low idle time",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bottomk(10, avg without(cpu, mode)(rate(node_cpu_seconds_total{mode=\"idle\"}[10m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 10 Nodes: Disk IO usage",
   "type": "graph",
   "description": "Top 10 nodes that use a lot of disk IO",
   "gridPos": { "h": 11, "w": 5, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (instance)(rate(node_disk_io_time_seconds_total[10m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nodes: Kernel versions",
   "type": "bargauge",
   "description": "Nodes: Kernel versions",
   "gridPos": { "h": 11, "w": 4, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum by (release)(node_uname_info)",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Nodes Network Receiving Bandwidth",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"bastion|eno[12]\"}[10m])",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Nodes Network Transmitting Bandwidth",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"bastion|eno[12]\"}[10m])",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Top 10 Nodes: High Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "topk(10, max by(instance) (node_hwmon_temp_celsius))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}