{
 "title": "Sabakan",
 "tags": [ "node" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(sabakan_assets_bytes_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy Machines",
   "type": "singlestat",
   "description": "The percentage of healthy machines",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * sum(max(sabakan_machine_status{status=\"healthy\"}) by (address, serial)) / sum(sabakan_machine_status{instance=\"10.69.0.3\"})"
    }
   ]
  },
  {
   "title": "Total Bytes of Assets",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sabakan_assets_bytes_total)"
    }
   ]
  },
  {
   "title": "Total Bytes of Images",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sabakan_images_bytes_total)"
    }
   ]
  },
  {
   "title": "Count of healthy machines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sabakan_machine_status{status=\"healthy\", instance=\"10.69.0.3\"})"
    }
   ]
  },
  {
   "title": "Count of not healthy machines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sabakan_machine_status{status!=\"healthy\", instance=\"10.69.0.3\"}) by (status)"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}