{
 "title": "Kubernetes Persistence Volumes",
 "description": "Kubernetes persistent volume inode and disk usage",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kubelet_volume_stats_inodes, instance)"
   },
   {
    "name": "persistentvolumeclaim",
    "label": "Persistent Volume Claim",
    "query": "label_values(kubelet_volume_stats_inodes{namespace=~\"$namespace\", instance=~\"$instance\"}, persistentvolumeclaim)"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Usage [%]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 / kubelet_volume_stats_capacity_bytes * kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$persistentvolumeclaim\", namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Disk Usage [bytes]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"$persistentvolumeclaim\", namespace=~\"$namespace\", instance=~\"$instance\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Inode Usage [%]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 / kubelet_volume_stats_inodes * kubelet_volume_stats_inodes_used{namespace=~\"$namespace\", persistentvolumeclaim=~\"$persistentvolumeclaim\", instance=~\"$instance\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Inode Usage [bytes]",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_inodes_free{namespace=~\"$namespace\", persistentvolumeclaim=~\"$persistentvolumeclaim\", instance=~\"$instance\"} / 1024 / 1024",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}