{
 "title": "Ceph - OSD (Single)",
 "description": "CEPH OSD Status.",
 "tags": [
  "ceph",
  "osd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "osd",
    "label": "OSD",
    "query": "label_values(ceph_osd_up, ceph_daemon)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(ceph_osd_up, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Status / Total OSDs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance) (ceph_osd_up{ceph_daemon=\"$osd\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Available",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (ceph_osd_in{ceph_daemon=\"$osd\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Total OSDs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (ceph_osd_up{namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "OSD: $osd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "PGs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (ceph_osd_numpg{ceph_daemon=\"$osd\", namespace=\"$namespace\"})",
       "legendFormat": "Number of PGs"
      },
      {
       "expr": "avg (ceph_osd_numpg{namespace=\"$namespace\"})",
       "legendFormat": "Average Number of PGs in the Cluster"
      }
     ]
    },
    {
     "title": "OSD Storage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 11, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (ceph_osd_stat_bytes{ceph_daemon=\"$osd\", namespace=\"$namespace\"}-ceph_osd_stat_bytes_used{ceph_daemon=\"$osd\", namespace=\"$namespace\"})",
       "legendFormat": "Available"
      },
      {
       "expr": "sum (ceph_osd_stat_bytes_used{ceph_daemon=\"$osd\", namespace=\"$namespace\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (ceph_osd_stat_bytes_used{ceph_daemon=\"$osd\", namespace=\"$namespace\"}/ceph_osd_stat_bytes{ceph_daemon=\"$osd\", namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency, Storage, Utilization Varience",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSD Apply Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum (ceph_osd_apply_latency_ms{ceph_daemon=\"$osd\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "OSD Commit Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum (ceph_osd_commit_latency_ms{ceph_daemon=\"$osd\", namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "OSD Read Op Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum (rate(ceph_osd_op_r_latency_sum{ceph_daemon=\"$osd\", namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_r_latency_count{ceph_daemon=\"$osd\", namespace=\"$namespace\"}[5m]) >= 0)"
      }
     ]
    },
    {
     "title": "OSD Write Op Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum (rate(ceph_osd_op_w_latency_sum{ceph_daemon=\"$osd\", namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_w_latency_count{ceph_daemon=\"$osd\", namespace=\"$namespace\"}[5m]) >= 0)"
      }
     ]
    },
    {
     "title": "Avg OSD  Op  Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg (rate(ceph_osd_op_r_latency_sum{ceph_daemon=\"$osd\", namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_r_latency_count{ceph_daemon=\"$osd\", namespace=\"$namespace\"}[5m]) >= 0)",
       "legendFormat": "read"
      },
      {
       "expr": "avg (rate(ceph_osd_op_w_latency_sum{ceph_daemon=\"$osd\", namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_w_latency_count{ceph_daemon=\"$osd\", namespace=\"$namespace\"}[5m]) >= 0)",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "AVG OSD Apply + Commit Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg (ceph_osd_apply_latency_ms{ceph_daemon=\"$osd\", namespace=\"$namespace\"})",
       "legendFormat": "apply"
      },
      {
       "expr": "avg (ceph_osd_commit_latency_ms{ceph_daemon=\"$osd\", namespace=\"$namespace\"})",
       "legendFormat": "commit"
      }
     ]
    }
   ]
  }
 ]
}