{
 "title": "Loki-Canary",
 "description": "Loki Canary is a standalone app that audits the log capturing performance of Loki.",
 "tags": [
  "loki",
  "loki-canary"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Missing entries rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_canary_missing_entries_total[1m])) by (instance\r)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Websocket missing entries rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_canary_websocket_missing_entries_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Websocket reconnects rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_canary_ws_reconnects_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Out of order entries rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_canary_out_of_order_entries_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unexpected entries rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_canary_unexpected_entries_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duplicate entries rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_canary_duplicate_entries_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average response latency [1m] per node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(loki_canary_response_latency_seconds_sum[1m]) / rate(loki_canary_response_latency_seconds_count[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response latency",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(loki_canary_response_latency_seconds_bucket[1m])"
    }
   ]
  },
  { "title": "Loki logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Loki logs",
   "type": "logs",
   "description": "anything except \"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\"",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{container=\"loki-canary\"} !~ \"^[0-9]+ [p]+\""
    }
   ]
  }
 ]
}