{
 "title": "Sabakan",
 "tags": [ "node" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(sabakan_assets_bytes_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Count of healthy machines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(sabakan_machine_status{status=\"healthy\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Count of not healthy machines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sum(sabakan_machine_status{status!=\"healthy\"}) by (status,instance)) by (status)"
    }
   ]
  },
  {
   "title": "Healthy Machines",
   "type": "singlestat",
   "description": "The percentage of healthy machines",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * max(sum(max(sabakan_machine_status{status=\"healthy\"}) by (address, serial,instance)) by (instance) / sum(sabakan_machine_status) by (instance))"
    }
   ]
  },
  {
   "title": "Total Bytes of Assets",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sabakan_assets_bytes_total)"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(sabakan_machine_status{status=\"unhealthy\"})by(address, role, rack, serial) > 0"
    }
   ]
  },
  {
   "title": "Unreachable Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "avg(sabakan_machine_status{status=\"unreachable\"})by(address, role, rack, serial) > 0"
    }
   ]
  },
  {
   "title": "Total Bytes of Images",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sabakan_images_bytes_total)"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(sabakan_api_request_count{instance=~\"$instance\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}